# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Define main pods.
def main_pods
  #Your common pods here
  pod 'AcrosureSDK', '~> 1.0'
end

target 'AcrosureSDKExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  main_pods
  # Pods for AcrosureSDKExample

end
